### ISSUE TITLE
更改chorddiagram机器人的code解析方式

### ISSUE THREAD

**Issue by xiGUAwanOU** [xiGUAwanOU/just-another-telegram-robot#1]
目前，chorddiagram机器人的code语法与URI语法基本一致，例如`p=xx1333`。目前的解析方式为使用Regex，但是Regex解析方式并不可靠。今后为了支持和弦的标题，code语法需要改成类似于`maj7?p=xx1333`这样的格式。这样code的语法就更加接近URI语法了。

目前的想法是，为了今后支持更多code的参数，或许我们可以利用[某些现成的工具](https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/client/utils/URLEncodedUtils.html)将code当作URI的一部分对其进行解析。从而解析类似于下面的code：
```
maj7?p=xx1333&t=,,i,r,r,r&s=1
```
并获取以下信息：
* 和弦的标题`maj7`
* 一个Map<String, String>包含下列信息：
  ```
  {
    "p": "xx1333",
    "t": ",,i,r,r,r"
  }
  ```

**Comment by xiGUAwanOU** [comment]
请参考 #8 - 支持新的code解析方式 ，从而确定哪些参数需要被解析。

**Comment by YuKitAs** [comment]
Done in 5daf00583659e7cfcdd8f8804dbe11d14760f4e8.
