### ISSUE TITLE
支持新的code解析方式

### ISSUE THREAD

**Issue by xiGUAwanOU** [xiGUAwanOU/just-another-telegram-robot#8]
目前code的解析方式并不尽如人意，下面是改进建议：

code解析的整体格式拟定为`title?p=&t=&f=&b=`其中：
  * `title`是和弦的标题，例如Dm、Cmaj7等；
  * `p`是和弦的指位，例如x00231，x表示不弹，0表示空弦，若0出现在其中，则`b`一定为0；
  * `t`是和弦的文字，例如x5r5r3，每一个字符对应一根弦的位置，若某一根弦处需要写两个字符，或不写任何字符，则用方括号括起，例如[]['5]r5[r'][3']，无方括号括起的部分依然是一个字符对应一根弦，这个参数为可选参数；
  * `f`表示使用的手指，例如---irm，这个参数为可选参数；
  * `b`表示起始的品数，只有当`p`中没有出现0的时候，`b`才可以不为0，这个参数为可选参数。

另外需要注意：之前版本中的`f`有另外的含义，现已更改；之前版本中的`s`参数现已取消。

**Comment by YuKitAs** [comment]
Done in 7bd7d1c3e0766983e6dbd4e9e97a09dc19c0d55d.

**Comment by xiGUAwanOU** [comment]
已完成于8fd2a5b18fdf01317c3abba986d67fc41c3617fa。
